// Signal Guard AI — Mock Data
// Used when real APIs aren't connected yet.
// Replace each section with real API calls as you configure keys.

export const MOCK_MARKET_OVERVIEW = {
  spy: { ticker: 'SPY', price: 742.41, previousClose: 738.18, changePercent: 0.57, volume: 20750000, high: 742.89, low: 735.47 },
  qqq: { ticker: 'QQQ', price: 714.71, previousClose: 707.24, changePercent: 1.06, volume: 37800000, high: 716.64, low: 704.89 },
  vix: 18.06,
  btc: { id: 'bitcoin', symbol: 'BTC', price: 80473, change24h: -1.83 },
  eth: { id: 'ethereum', symbol: 'ETH', price: 2290, change24h: -2.11 },
  timestamp: new Date().toISOString(),
}

export const MOCK_SIGNALS = [
  {
    id: 'sig_001',
    ticker: 'SPY',
    marketType: 'stock',
    direction: 'long',
    totalScore: 72,
    grade: 'B',
    scoreTrend: 9, scoreMaAlign: 8, scoreSupRes: 6, scoreVolume: 6,
    scoreMomentum: 7, scoreRsiMacd: 6, scoreVwap: 7, scoreBreakout: 5,
    scoreNewsRisk: 7, scoreVolatility: 8, scoreRrRatio: 7,
    shouldSkip: false,
    skipReason: null,
    aiReasoning: 'SPY is in a confirmed uptrend hitting all-time highs. Score is borderline B because entry is extended — needs pullback to VWAP before entry is valid.',
    scanDate: new Date().toISOString(),
  },
  {
    id: 'sig_002',
    ticker: 'QQQ',
    marketType: 'stock',
    direction: 'long',
    totalScore: 74,
    grade: 'B',
    scoreTrend: 9, scoreMaAlign: 8, scoreSupRes: 7, scoreVolume: 7,
    scoreMomentum: 8, scoreRsiMacd: 7, scoreVwap: 7, scoreBreakout: 6,
    scoreNewsRisk: 7, scoreVolatility: 8, scoreRrRatio: 7,
    shouldSkip: false,
    skipReason: null,
    aiReasoning: 'QQQ outperforming SPY today (+1.06%). Tech sector leading. Pullback to $708–$710 VWAP level is the entry trigger. Do not chase above $714.',
    scanDate: new Date().toISOString(),
  },
  {
    id: 'sig_003',
    ticker: 'BTC',
    marketType: 'crypto',
    direction: 'skip',
    totalScore: 58,
    grade: 'C',
    scoreTrend: 4, scoreMaAlign: 5, scoreSupRes: 5, scoreVolume: 6,
    scoreMomentum: 4, scoreRsiMacd: 5, scoreVwap: 6, scoreBreakout: 3,
    scoreNewsRisk: 8, scoreVolatility: 6, scoreRrRatio: 6,
    shouldSkip: true,
    skipReason: 'Score 58/100 — below 70 minimum. BTC making lower highs. Hot CPI reducing rate-cut expectations. No clean setup.',
    aiReasoning: 'BTC has been in a short-term downtrend since Monday. Lower highs at $82K, $81.5K, $80.5K. No bullish setup visible. Wait for reclaim of $82,000 or a flush to $77K–$78K support.',
    scanDate: new Date().toISOString(),
  },
  {
    id: 'sig_004',
    ticker: 'AAPL',
    marketType: 'stock',
    direction: 'long',
    totalScore: 71,
    grade: 'B',
    scoreTrend: 8, scoreMaAlign: 8, scoreSupRes: 7, scoreVolume: 6,
    scoreMomentum: 7, scoreRsiMacd: 6, scoreVwap: 7, scoreBreakout: 6,
    scoreNewsRisk: 8, scoreVolatility: 8, scoreRrRatio: 7,
    shouldSkip: false,
    skipReason: null,
    aiReasoning: 'AAPL above all major MAs. Consolidating near $184. VWAP entry valid if pulls to $183.80–$184.20. No earnings risk this week.',
    scanDate: new Date().toISOString(),
  },
]

export const MOCK_TRADE_PLANS = [
  {
    id: 'plan_001',
    signalId: 'sig_001',
    ticker: 'SPY',
    marketType: 'stock',
    action: 'buy',
    bias: 'long',
    entryLow: 738.00,
    entryHigh: 739.50,
    stopLoss: 736.00,
    takeProfit1: 742.50,
    takeProfit2: 745.00,
    rrRatio: 2.1,
    accountSize: 500.00,
    riskDollars: 4.50,
    positionSize: 1.5,
    maxDollarRisk: 5.00,
    tradeReason: 'SPY pullback to VWAP in confirmed uptrend. Volume declining on pullback (healthy). RSI has room to run from 52. Breakout above $742 is continuation signal.',
    invalidation: 'SPY breaks below $736 on volume, or broad market turns negative on unexpected news.',
    confidenceScore: 72,
    plainEnglish: 'SPY is at all-time highs but we\'re waiting for a small dip back to $738–$739. That dip is the entry. Stop is below today\'s support at $736. Target is back at today\'s high ($742.50) and then $745. Risk is $4.50 on a $500 paper account — well within the 1% rule.',
    passedRiskCheck: true,
    riskViolations: [],
    userApproved: null,
    planDate: new Date().toISOString(),
  },
]

export const MOCK_JOURNAL_ENTRIES = [
  {
    id: 'journal_001',
    entryDate: new Date(Date.now() - 86400000).toISOString(),
    marketType: 'stock',
    ticker: 'QQQ',
    strategyName: 'VWAP Pullback',
    entryPrice: 707.50,
    exitPrice: 711.20,
    stopLossUsed: 705.00,
    takeProfitHit: 'TP1',
    positionSize: 1.96,
    pnlDollars: 7.25,
    pnlPercent: 2.04,
    setupScore: 74,
    tradeMode: 'paper',
    followedPlan: true,
    movedStop: false,
    chasedEntry: false,
    revengeTrade: false,
    emotionBefore: 'calm',
    myReasoning: 'QQQ pulled back to VWAP exactly as planned. Volume dried up on the pullback. Entered on first green candle.',
    lessonLearned: 'Patience works. Waited 45 minutes for the entry instead of chasing the open.',
  },
]

export const MOCK_PERFORMANCE = {
  totalTrades: 12,
  paperTrades: 12,
  liveTrades: 0,
  wins: 7,
  losses: 5,
  winRate: 58.3,
  avgWin: 8.42,
  avgLoss: -4.15,
  profitFactor: 2.03,
  expectancy: 3.21,
  maxDrawdown: -11.40,
  totalPnl: 28.19,
  bestMarket: 'stock',
  worstMarket: 'crypto',
  ruleViolations: 2,
  noTradeCorrectDays: 3,
}

export const MOCK_BRIEFING = {
  marketBias: 'bullish' as const,
  biasReason: 'SPY +0.57% and QQQ +1.06%. Market pushing all-time highs. Bullish bias but extended — pullback entries only.',
  spyChange: 0.57,
  qqqChange: 1.06,
  btcChange: -1.83,
  ethChange: -2.11,
  vixLevel: 18.06,
  volatilityWarn: false,
  highImpactNews: ['Check investing.com/economic-calendar for today\'s events', 'PPI tomorrow 8:30 AM — do not hold overnight'],
  noTradeReasons: [],
  bestWindow: '10:00 AM – 11:30 AM ET',
  fullBriefing: 'Market is at all-time highs today despite hotter-than-expected CPI yesterday. SPY and QQQ are leading. BTC is weak. VIX is normal at 18. Best window is mid-morning after the open noise settles. Wait for pullback entries — do not chase. Max 2 trades today. Paper mode active.',
  topSetupIds: ['sig_001', 'sig_002'],
}
